Repository PopulateTools/gobierto, pull requests merged in 2021-05, with the labels that each got.

#3858 Gobierto Data / fix dataset source & license with urls
  app/javascript/gobierto_data/webapp/components/commons/Info.vue
  app/javascript/gobierto_data/webapp/components/commons/InfoBlockLink.vue
  app/javascript/gobierto_data/webapp/components/commons/InfoBlockText.vue
  app/javascript/gobierto_data/webapp/components/commons/LinkableText.vue
  app/javascript/gobierto_data/webapp/components/sets/SummaryTab.vue
  db/seeds/gobierto_seeds/gobierto_data/recipe.rb
Labels: gobierto-data

#3874 Gobierto Visualizations / Improvements the perfomance of the table
  app/javascript/lib/vue/components/modules/Table.vue
Labels: gobierto-visualizations

#3886 Gobierto Data / Update perspective-map: 1.0.3 → 1.0.4
  package.json
  yarn.lock
Labels: gobierto-data

#3884 Gobierto Visualizations / Improves the usability of the subsidies table
  app/javascript/gobierto_visualizations/webapp/containers/subsidies/SubsidiesIndex.vue
  app/javascript/gobierto_visualizations/webapp/lib/config/subsidies.js
  config/locales/gobierto_visualizations/views/ca.yml
  config/locales/gobierto_visualizations/views/en.yml
  config/locales/gobierto_visualizations/views/es.yml
  test/integration/gobierto_visualizations/visualizations_subsidies_test.rb
Labels: gobierto-visualizations

#3896 Gobierto Data / Fix embed vizualitions
  app/javascript/gobierto_embeds/index.js
Labels: bug
